### PR TITLE
Fix eslint-config, add github action, fix lint issues

### LINKED ISSUE #74: "npm run build" errors
**editor.js\example\tools\image>npm run build**

> ERROR in ./src/index.js
> Module build failed (from ./node_modules/eslint-loader/index.js):
> Error: ESLint configuration in C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint-config-codex\configs\ts.json is invalid:
>         - Unexpected top-level property "overrides[0].extends".
> 
> Referenced from: C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint-config-codex\index.js
> Referenced from: C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\.eslintrc
>     at validateConfigSchema (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\config\config-validator.js:235:15)
>     at Object.validate (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\config\config-validator.js:261:5)
>     at loadFromDisk (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\config\config-file.js:544:19)    
>     at load (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\config\config-file.js:587:20)
>     at C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\config\config-file.js:453:36
>     at Array.reduceRight (<anonymous>)
>     at applyExtends (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\config\config-file.js:431:26)    
>     at loadFromDisk (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\config\config-file.js:551:22)    
>     at load (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\config\config-file.js:587:20)
>     at C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\config\config-file.js:453:36
>     at Array.reduceRight (<anonymous>)
>     at applyExtends (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\config\config-file.js:431:26)    
>     at loadFromDisk (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\config\config-file.js:551:22)    
>     at Object.load (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\config\config-file.js:587:20)     
>     at Config.getLocalConfigHierarchy (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\config.js:240:44)
>     at Config.getConfigHierarchy (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\config.js:192:43)   
>     at Config.getConfigVector (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\config.js:299:21)      
>     at Config.getConfig (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\config.js:342:29)
>     at processText (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\cli-engine.js:181:33)
>     at CLIEngine.executeOnText (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint\lib\cli-engine.js:690:40) 
>     at lint (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint-loader\index.js:278:17)
>     at Object.module.exports (C:\Users\q4rockz\Documents\GitHub\editor.js\example\tools\image\node_modules\eslint-loader\index.js:273:21)     
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! @editorjs/image@2.3.1 build: `webpack --mode production`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the @editorjs/image@2.3.1 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\q4rockz\AppData\Roaming\npm-cache\_logs\2020-04-22T04_05_42_945Z-debug.log

### PR DESCRIPTION
**Pull request by neSpecc**
- Upgrade ESLint version 
- Renew [ESLint CodeX](https://github.com/codex-team/eslint-config) config
- Fix ESLint issues
- Add GitHub action for linting

Resolves #74

### CODE REVIEW

File: src/ui.js [hunk 1]
```diff
@@ -46,7 +47,8 @@ export default class Ui {
 
   /**
    * CSS classes
-   * @constructor
+   *
+   * @class
```
Comment (khaydarov) [inline src/ui.js:51]: @class annotation is intended to be called with the "new" keyword, it is inappropriate here

File: src/index.js [hunk 2]
```diff
@@ -79,19 +80,20 @@ export default class ImageTool {
...
-      title: 'Image'
+      title: 'Image',
     };
   }
 
   /**
-   * @param {ImageToolData} data - previously saved data
-   * @param {ImageConfig} config - user config for Tool
-   * @param {object} api - Editor.js API
+   * @param {object} tool - tool properties got from editor.js
```
Comment (khaydarov) [inline src/index.js:93]: we used typedefs in JS to describe non-primitive types

```js
@typedef tool
@property ....
```

File: src/index.js [hunk 3]
```diff
@@ -151,19 +153,21 @@ export default class ImageTool {
 
   /**
    * Renders Block content
+   *
    * @public
```
Comment (khaydarov) [inline src/index.js:157]: such annotations do not make a sense because all class functions are public whatever we write, even if write `private` it won't make them private

File: src/index.js [hunk 4]
```diff
@@ -242,18 +252,19 @@ export default class ImageTool {
 
         this.uploadUrl(image.src);
         break;
-
-      case 'pattern':
+      }
+      case 'pattern': {
```
Comment (khaydarov) [inline src/index.js:256]: These brackets make sense if logic in the case is complex. For now, it looks like extra useless code manipulation when you could just write `this.upload(event.data.data)` - nothing will change, because the code below doesn't have any conditions

File: src/index.js (hunk 2 above)
Comment (neSpecc) [reply src/index.js:93]: it is just function parameters, because jsdoc plugin does not support destructuring assignment

https://github.com/gajus/eslint-plugin-jsdoc/issues/11

File: src/index.js (hunk 3 above)
Comment (neSpecc) [reply src/index.js:157]: it is an example plugin, so these annotations intended for developers for better understanding what is a Block API and what is tool stuff that can be implemented by their own way

File: src/index.js (hunk 4 above)
Comment (neSpecc) [reply src/index.js:256]: they are used to support `const` and `let` block-scoping

https://eslint.org/docs/rules/no-case-declarations

File: src/index.js (hunk 3 above)
Comment (khaydarov) [reply src/index.js:157]: But it is not about OOP principles and the Block's API is written in EditorJS documentation. These annotations are more abstract stuff.

File: src/index.js (hunk 4 above)
Comment (khaydarov) [reply src/index.js:256]: they, indeed, but it doesn't make this recommendation important )

Comment (neSpecc) [reply src/index.js:256]: and the variables used for better understanding of how `onPaste` works
